---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: polymorphic
  namespace: hussain-flux-helm
spec:
  interval: 1m0s
  url: https://annavar-satish.github.io/helm-charts/

