---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: scrumwala
  namespace: hussain-flux
spec:
  interval: 1m0s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: scrumwala
    namespace: hussain-flux
  targetNamespace: hussain-flux

