---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: hussain-flux-helm
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redis
  interval: 1m0s
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2