---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: mattermost-bot-alert
  namespace: hussain-flux
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  # - kind: ImagePolicy
  #   name: '*'
  providerRef:
    name: mattermost

